package:
  name: r-matrix
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.2_3"

source:
  fn: Matrix_1.2-3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/Matrix_1.2-3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.2-3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 3caed93a21b9ce3e51773dd80603961f
  # sha1: 264c309b91f81df4e6f0b00b58c17b481376bb08
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: expm, MASS
requirements:
  build:
    - r-base
    - r-lattice # [not win]
    - gcc # [not win]

  run:
    - r
    - r-lattice # [not win]
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('Matrix')" # [not win]
    - "\"%R%\" -e \"library('Matrix')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://Matrix.R-forge.R-project.org/
  license: GPL (>= 2)
  summary: Classes and methods for dense and sparse matrices and operations on them using 'LAPACK'
    and 'SuiteSparse'.

# The original CRAN metadata for this package was:

# Package: Matrix
# Version: 1.2-3
# Date: 2015-11-19
# Priority: recommended
# Title: Sparse and Dense Matrix Classes and Methods
# Author: Douglas Bates <bates@stat.wisc.edu> and Martin Maechler
# Maintainer: Martin Maechler <mmaechler+Matrix@gmail.com>
# Contact: Doug and Martin <Matrix-authors@R-project.org>
# Description: Classes and methods for dense and sparse matrices and operations on them using 'LAPACK' and 'SuiteSparse'.
# Depends: R (>= 3.0.1)
# Imports: methods, graphics, grid, stats, utils, lattice
# Suggests: expm, MASS
# Enhances: MatrixModels, graph, SparseM, sfsmisc
# Encoding: UTF-8
# LazyData: no
# LazyDataNote: not possible, since we use data/*.R *and* our classes
# ByteCompile: yes
# BuildResaveData: no
# License: GPL (>= 2)
# LicenseNote: The Matrix package includes libraries AMD, CHOLMOD, COLAMD, CSparse and SPQR from the SuiteSparse collection of Tim Davis.  All sections of that code are covered by the GPL or LGPL licenses.  See the directory doc/UFsparse for details.
# URL: http://Matrix.R-forge.R-project.org/
# NeedsCompilation: yes
# Packaged: 2015-11-27 14:50:41 UTC; maechler
# Repository: CRAN
# Date/Publication: 2015-11-28 14:44:50
# 

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
